CREATE TABLE IF NOT EXISTS "Stage" (
	"StageId" INTEGER,
	"Number" INTEGER NOT NULL,
	"BoardId" INTEGER NOT NULL,
	"Title" TEXT NOT NULL,
	"Description" TEXT,
	"TaskLimit" INTEGER,
	PRIMARY KEY("StageId" AUTOINCREMENT),
	FOREIGN KEY("BoardId") REFERENCES "Board"("BoardId")
);